/// Flutter icons RpsIcon
/// Copyright (C) 2020 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  RpsIcon
///      fonts:
///       - asset: fonts/RpsIcon.ttf
///
///
/// * Font Awesome 5, Copyright (C) 2016 by Dave Gandy
///         Author:    Dave Gandy
///         License:   SIL (https://github.com/FortAwesome/Font-Awesome/blob/master/LICENSE.txt)
///         Homepage:  http://fortawesome.github.com/Font-Awesome/
///
import 'package:flutter/widgets.dart';

class RpsIcon {
  RpsIcon._();

  static const _kFontFam = 'RpsIcon';
  static const _kFontPkg = null;

  static const IconData paper_plane = IconData(0xf1d8, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData hand_rock = IconData(0xf255, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData hand_scissors = IconData(0xf257, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
